complaint:
    resource: "@ComplaintBundle/Resources/config/routing.yml"
recommendation:
    resource: "@RecommendationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
