add_complaint:
    path:     /addComplaint/{iduser}/{idType}
    defaults: { _controller: ComplaintBundle:Complaint:add }
get_complaint:
    path:     /getComplaint/{id}
    defaults: { _controller: ComplaintBundle:Complaint:getComplaintById }
get_complaints:
    path:     /getComplaints
    defaults: { _controller: ComplaintBundle:Complaint:getComplaints }
update_complaint:
    path:     /updateComplaint/{id}
    defaults: { _controller: ComplaintBundle:Complaint:updateComplaint }
delete_complaint:
    path:     /deleteComplaint/{id}
    defaults: { _controller: ComplaintBundle:Complaint:deleteComplaint }
add_type:
    path:     /addType
    defaults: { _controller: ComplaintBundle:Type:addType }
get_type:
    path:     /getById/{id}
    defaults: { _controller: ComplaintBundle:Type:getTypeById }
get_all:
    path:     /getAll
    defaults: { _controller: ComplaintBundle:Type:getAllTypes }
update_type:
    path:     /updateType/{id}
    defaults: { _controller: ComplaintBundle:Type:updatetype }
delete_type:
    path:     /deleteType/{id}
    defaults: { _controller: ComplaintBundle:Type:deleteType }